version: "3"
services:
  db:
    image: "postgres:11.6"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=hilly-sand-pit
      - POSTGRES_DB=prisma
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  app:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env

  cypress:
    image: "cypress/included:3.4.0"
    container_name: "cypress"
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app:3000
    working_dir: /e2e
    volumes:
      - ./:/e2e